"""GeoMaskLab prototype: traceable sessions, real geometry, explicit demo/live modes."""
from __future__ import annotations
import base64
import csv
import hashlib
import io
import json
import os
import re
import threading
import time
import uuid
import zipfile
from workbench.pixel_geometry import candidate_statistics, scope_area_pixels
from datetime import datetime, timezone
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from PIL import Image, ImageDraw, ImageOps
from workbench.runtime_config import load_settings, settings_status
from workbench.service_transport import request_json, inspect_services
from workbench.product_contract import VERSION, TARGET_CAPABILITIES, capabilities
from workbench.semantic_review import initial_review, append_review
from workbench.agent_bridge import AgentTurn, Clarification, decision_record, resolve_scope, segmentation_plan
from workbench.v07_contract import batch_requested, has_target_intent, resolve_quality, resolve_roi, target_intent, validate_target_intent
from workbench.task_grammar import ambiguous_query, is_export_command

load_settings()

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / 'workbench/web'
DATA = ROOT / 'experiments'
DATA.mkdir(exist_ok=True)
SESSIONS = {}
BATCHES = {}
LOCK = threading.RLock()
SID_RE = re.compile(r'^[a-f0-9]{12}$')
SIDES = {'all': 'Whole image', 'left': 'Left half', 'right': 'Right half', 'top': 'Top half', 'bottom': 'Bottom half'}
TARGETS = {'building': 'Buildings', 'aircraft': 'Aircraft', 'road': 'Roads', 'water': 'Water', 'tree': 'Vegetation', 'ship': 'Ships'}
DESCRIPTIONS = {'building':'all buildings','aircraft':'all planes','road':'all roads','water':'water bodies','tree':'trees and vegetation','ship':'all ships'}
SAMPLES = {
 'urban': {'name': 'Synthetic urban example', 'file': 'urban.png', 'target': 'building', 'size': [800,600],
  'source': 'Synthetic urban diagram generated by GeoMaskLab fixtures.py; demonstrates pixel operations, not remote-sensing observations or model predictions.',
  'scene': 'This procedural urban diagram contains buildings, roads and green spaces. Try extracting buildings and comparing the two image halves. This scene description is preset example text, not a model response.'},
 'airport': {'name': 'Synthetic aircraft example', 'file': 'airport.jpg', 'target': 'aircraft', 'size': [800,800],
  'source': 'Synthetic aircraft diagram generated by GeoMaskLab fixtures.py; demonstrates pixel operations, not remote-sensing observations or model predictions.',
  'scene': 'This procedural diagram contains two aircraft shapes. Try extracting either half and calculating pixel coverage. This scene description is preset example text, not a model response.'},
}

def uid(): return uuid.uuid4().hex[:12]
def now(): return datetime.now(timezone.utc).isoformat()
def save_json(path, value):
    temporary=path.with_name(path.name+'.'+uid()+'.tmp')
    temporary.write_text(json.dumps(value,ensure_ascii=False,indent=2),encoding='utf-8')
    os.replace(temporary,path)
def image_b64(image):
    b=io.BytesIO(); image.save(b,format='PNG'); return base64.b64encode(b.getvalue()).decode()

def demo_mask(sample):
    """Exact procedural fixture mask; not an EO model prediction."""
    from workbench.fixtures import fixture
    return fixture(sample)[1]

from geomasklab.measurements import constrain, foreground_area, statistics

def experiment_report(session, result):
    """Delegate report rendering to the pure English report module."""
    from workbench.report_builder import build_report
    return build_report(session, result, TARGETS, SIDES, TARGET_CAPABILITIES)


def batch_csv(batch):
    output=io.StringIO(newline='')
    writer=csv.writer(output)
    writer.writerow(['session_id','run_id','status','pixel_area','area_ratio','candidate_count','duration_ms','failure_reason'])
    for item in batch['items']:
        metrics=item.get('metrics') or {}
        writer.writerow([item['session_id'],item.get('run_id'),item['status'],metrics.get('pixel_area'),
                         metrics.get('area_ratio'),(metrics.get('candidate_stats') or {}).get('candidate_count'),
                         item.get('duration_ms'),item.get('failure_reason')])
    return '\ufeff'+output.getvalue()

def parse_task(query, context):
    """Backward-compatible entry point for the procedural-demo grammar."""
    from workbench.task_grammar import parse_demo_task
    return parse_demo_task(query, context)


def requires_dense_result(query, context=None):
    from workbench.task_grammar import requires_dense_result as dense_intent
    return dense_intent(query, context)


def resolve_invert(query, context=None):
    from workbench.task_grammar import resolve_invert as complement_intent
    return complement_intent(query, context)


def post_json(url,payload,timeout=120,headers=None):
    return request_json(url,payload,timeout,headers)

def public_session(s):
    return {k:v for k,v in s.items() if k not in ('lock',)}

def get_session(sid):
    if not isinstance(sid,str) or not SID_RE.fullmatch(sid): return None
    with LOCK:
        if sid in SESSIONS: return SESSIONS[sid]
        folder=DATA/sid
        try:
            s=json.loads((folder/'session.json').read_text(encoding='utf-8'))
            if s.get('id')!=sid or not (folder/'original.png').is_file(): return None
            if not isinstance(s.get('runs'),list) or not isinstance(s.get('context'),dict): return None
            if any(not isinstance(s.get(k),str) for k in ('name','created_at','image_url','source')): return None
            if any(type(s.get(k)) is not int or s[k]<=0 for k in ('width','height')): return None
            for r in s['runs']:
                if not SID_RE.fullmatch(r.get('id','')) or r.get('session_id')!=sid: return None
            s['lock']=threading.Lock(); SESSIONS[sid]=s; return s
        except (OSError,ValueError,TypeError,AttributeError): return None

def session_index():
    items=[]
    for folder in DATA.iterdir():
        if not folder.is_dir() or not SID_RE.fullmatch(folder.name): continue
        s=get_session(folder.name)
        if s:
            items.append({k:s[k] for k in ('id','name','created_at','width','height')})
            items[-1]['run_count']=len(s['runs'])
            items[-1].update(notes=s.get('notes',''),pinned=s.get('pinned',False),
                mask_count=sum(bool(r.get('mask_url')) for r in s['runs']),
                pending_count=sum(bool(r.get('mask_url')) and r.get('semantic_review',{}).get('state','pending')=='pending' for r in s['runs']))
    return sorted(items,key=lambda item:item['created_at'],reverse=True)[:100]

def binary_mask(mask):
    mask=mask.convert('L'); values={i for i,count in enumerate(mask.histogram()) if count}
    if values.issubset({0,1}): return mask.point(lambda value:255 if value else 0)
    if values.issubset({0,255}): return mask
    raise ValueError('RemoteSAM must return a 0/1 or 0/255 binary mask. Probability maps and multiclass labels cannot be measured as target area.')

def mask_cache_key(s,mode,target,service_request=None):
    revision='synthetic-fixtures-v1' if mode=='demo' else os.environ.get('GEO_REMOTESAM_REVISION','')
    if not revision: return None  # Unknown live model revision cannot be safely reused.
    value={'image':hashlib.sha256((DATA/s['id']/'original.png').read_bytes()).hexdigest(),
           'mode':mode,'target':target,'prompt':DESCRIPTIONS[target],'revision':revision,
           'endpoint':os.environ.get('GEO_REMOTESAM_URL','') if mode=='live' else '',
           'service_request':service_request}
    return hashlib.sha256(json.dumps(value,sort_keys=True).encode()).hexdigest()

def new_session(sample='urban',uploaded=None,name=None):
    sid=uid(); folder=DATA/sid; folder.mkdir()
    if uploaded is None:
        if sample not in SAMPLES: raise ValueError('Unknown example.')
        image=Image.open(WEB/'assets'/SAMPLES[sample]['file']).convert('RGB')
    else:
        raw=base64.b64decode(uploaded.split(',')[-1],validate=True)
        if len(raw)>12*1024*1024: raise ValueError('Images must be 12 MB or smaller.')
        image=Image.open(io.BytesIO(raw))
        if image.width*image.height>16_000_000: raise ValueError('Images must contain no more than 16 million pixels.')
        image=ImageOps.exif_transpose(image).convert('RGB'); sample=None
    image.save(folder/'original.png')
    s={'id':sid,'sample':sample,'name':(name or (SAMPLES[sample]['name'] if sample else 'Uploaded image'))[:120], 'width':image.width,'height':image.height,
       'image_url':f'/experiments/{sid}/original.png','created_at':now(),'runs':[], 'context':{},
       'source':SAMPLES[sample]['source'] if sample else 'User-uploaded image', 'lock':threading.Lock()}
    with LOCK: SESSIONS[sid]=s
    save_json(folder/'session.json',public_session(s)); return public_session(s)

def run_task(s,p,allow_batch=False):
    if p.get('batch_id') and not allow_batch:
        raise ValueError('Only the batch executor may assign batch_id.')
    if not s['lock'].acquire(blocking=False): raise ValueError('This session is busy. Wait for the current task to finish.')
    try: return _run_task(s,p,allow_batch=allow_batch)
    finally: s['lock'].release()

def import_evidence(p):
    """Open verified evidence in a new local session and retain the original ZIP."""
    from workbench.evidence_handoff import prepare_import
    encoded=p.get('bundle')
    if not isinstance(encoded,str) or len(encoded)>16*1024*1024:
        raise ValueError('Upload an evidence bundle no larger than 12 MB.')
    try:
        payload=base64.b64decode(encoded.split(',')[-1],validate=True)
        result,files,facts=prepare_import(payload)
    except (ValueError,zipfile.BadZipFile,OSError) as error:
        raise ValueError('Cannot import evidence: '+str(error)) from error
    if not isinstance(result['metrics'].get('candidate_stats'),dict):
        raise ValueError('This bundle has no candidate-component statistics and cannot be restored.')
    name=p.get('name','Imported evidence')
    if not isinstance(name,str): raise ValueError('Invalid file name.')
    sid=uid();rid=result['id'];folder=DATA/sid;run_folder=folder/rid
    s={'id':sid,'sample':None,'name':('Imported · '+name)[:120],
       'width':facts['width'],'height':facts['height'],'created_at':now(),
       'image_url':f'/experiments/{sid}/original.png','context':{},'runs':[result],
       'source':result['provenance']['source'],'imported_evidence':result['imported_evidence'],
       'lock':threading.Lock()}
    base=f'/experiments/{sid}/{rid}'
    result.update(session_id=sid,mask_url=base+'/mask.png',overlay_url=base+'/overlay.png',
                  export_url=f'/api/export/{sid}/{rid}',report_url=f'/api/report/{sid}/{rid}')
    try: report=experiment_report(s,result)
    except (KeyError,TypeError,AttributeError) as error:
        raise ValueError('The report fields are incomplete or unsupported.') from error
    run_folder.mkdir(parents=True)
    (folder/'original.png').write_bytes(files['original.png'])
    (folder/'source-evidence.zip').write_bytes(payload)
    for file in ('full_mask.png','mask.png','overlay.png','statistics.json','run_log.json'):
        (run_folder/file).write_bytes(files[file])
    for name in ('source_mask.png','analysis.json','valid_mask.png','source_valid_mask.png'):
        if name in files:(run_folder/name).write_bytes(files[name])
    save_json(run_folder/'result.json',{k:v for k,v in result.items() if k!='trace'})
    (run_folder/'report.md').write_text(report,encoding='utf-8')
    save_json(folder/'session.json',public_session(s))
    with LOCK: SESSIONS[sid]=s
    return public_session(s)

def review_result(s, payload):
    rid=payload.get('run_id')
    if not isinstance(rid,str) or not SID_RE.fullmatch(rid): raise ValueError('Invalid run ID.')
    if not s['lock'].acquire(blocking=False): raise ValueError('This session is busy. Wait before recording a review.')
    try:
        result=next((r for r in s['runs'] if r['id']==rid),None)
        if not result or not result.get('mask_url') or result['status'] not in ('completed','needs_review'):
            raise ValueError('Select a valid mask result from this image before reviewing.')
        folder=DATA/s['id']/rid
        review=append_review(result.get('semantic_review'),payload,at=now(),run_id=rid,
                             image_bytes=(DATA/s['id']/'original.png').read_bytes(),
                             mask_bytes=(folder/'mask.png').read_bytes())
        updated={**result,'semantic_review':review}
        save_json(folder/'result.json',{k:v for k,v in updated.items() if k!='trace'})
        (folder/'report.md').write_text(experiment_report(s,updated),encoding='utf-8')
        result.update(semantic_review=review)
        save_json(DATA/s['id']/'session.json',public_session(s))
        return result
    finally: s['lock'].release()


def recalculate_region(s, payload):
    """Create a separate spatial-analysis version without invoking model services."""
    from workbench.export_bundle import build_bundle
    from workbench.region_analysis import prepare_analysis
    if set(payload)-{'session_id','run_id','scope','roi','validity_action','valid_mask','valid_source'}:
        raise ValueError('Offline region analysis accepts only a source run and spatial scope; it cannot change the semantic target.')
    rid=payload.get('run_id')
    if not isinstance(rid,str) or not SID_RE.fullmatch(rid):
        raise ValueError('Invalid source run ID.')
    if not s['lock'].acquire(blocking=False):
        raise ValueError('This session is busy. Wait for the current operation to finish.')
    try:
        source=next((r for r in s['runs'] if r['id']==rid),None)
        if not source or not source.get('mask_url'):
            raise ValueError('Select an existing mask result in this session.')
        source_folder=DATA/s['id']/rid
        bundle=build_bundle(DATA/s['id']/'original.png',source_folder)
        from geomasklab.domain import KEEP_VALIDITY
        from workbench.mask_inputs import decode_mask
        action=payload.get('validity_action','keep')
        if action not in ('keep','replace','all_valid'):raise ValueError('Choose keep, replace or all_valid for validity.')
        if action!='replace' and (payload.get('valid_mask') is not None or payload.get('valid_source') is not None):
            raise ValueError('Validity uploads require the replace action.')
        valid=decode_mask(payload.get('valid_mask')) if action=='replace' else None if action=='all_valid' else KEEP_VALIDITY
        runid=uid()
        result,files=prepare_analysis(bundle,payload.get('scope','all'),payload.get('roi'),
            run_id=runid,created_at=now(),version=len(s['runs'])+1,
            statistics=statistics,constrain=constrain,valid_mask=valid,valid_source=payload.get('valid_source'))
        if result['session_id']!=s['id'] or result['parent_run_id']!=rid:
            raise ValueError('The saved result does not belong to this session.')
        base=f'/experiments/{s["id"]}/{runid}'
        result.update(mask_url=base+'/mask.png',overlay_url=base+'/overlay.png',
            export_url=f'/api/export/{s["id"]}/{runid}',report_url=f'/api/report/{s["id"]}/{runid}')
        report=experiment_report(s,result)
        folder=DATA/s['id']/runid
        folder.mkdir()
        for name,raw in files.items(): (folder/name).write_bytes(raw)
        save_json(folder/'statistics.json',result['metrics'])
        save_json(folder/'result.json',{k:v for k,v in result.items() if k!='trace'})
        save_json(folder/'run_log.json',result['trace'])
        (folder/'report.md').write_text(report,encoding='utf-8')
        s['runs'].append(result)
        task=result['task']
        s['context']={key:task.get(key) for key in ('target','side','invert','roi','quality_mode')}
        save_json(DATA/s['id']/'session.json',public_session(s))
        return result
    finally:
        s['lock'].release()

def import_mask(s, payload):
    """Adapt an explicit mask upload to the same evidence core used by the CLI."""
    from workbench.mask_inputs import decode_mask
    from geomasklab.api import create_evidence
    from geomasklab.evidence import load_verified_bundle
    if set(payload)-{'session_id','mask','target','source','parent_run_id','aligned','valid_mask','valid_source'}:
        raise ValueError('Unsupported mask-import field.')
    if payload.get('aligned') is not True:
        raise ValueError('Confirm pixel alignment with the displayed image before importing.')
    raw=decode_mask(payload.get('mask'))
    valid=decode_mask(payload['valid_mask']) if payload.get('valid_mask') is not None else None
    if not s['lock'].acquire(blocking=False):raise ValueError('This experiment is busy.')
    try:
        parent=payload.get('parent_run_id')
        if parent is not None and not any(r['id']==parent and r.get('mask_url') for r in s['runs']):
            raise ValueError('The parent must be a mask result in this experiment.')
        rid=uid()
        bundle=create_evidence((DATA/s['id']/'original.png').read_bytes(),raw,
            target=payload.get('target'),source=payload.get('source'),aligned=True,
            image_source=s['source'],session_id=s['id'],run_id=rid,parent_run_id=parent,version=len(s['runs'])+1,
            valid_mask=valid,valid_source=payload.get('valid_source'))
        _,files=load_verified_bundle(bundle)
        result=json.loads(files['result.json']);result['trace']=json.loads(files['run_log.json'])
        base=f'/experiments/{s["id"]}/{rid}'
        result.update(mask_url=base+'/mask.png',overlay_url=base+'/overlay.png',
            export_url=f'/api/export/{s["id"]}/{rid}',report_url=f'/api/report/{s["id"]}/{rid}')
        report=experiment_report(s,result)
        folder=DATA/s['id']/rid;folder.mkdir()
        for name in ('source_mask.png','full_mask.png','mask.png','overlay.png','statistics.json','run_log.json'):
            (folder/name).write_bytes(files[name])
        for name in ('analysis.json','valid_mask.png','source_valid_mask.png'):
            if name in files:(folder/name).write_bytes(files[name])
        save_json(folder/'result.json',{k:v for k,v in result.items() if k!='trace'})
        (folder/'report.md').write_text(report,encoding='utf-8')
        s['runs'].append(result);s['context']={k:result['task'].get(k) for k in ('target','side','invert','roi','quality_mode')}
        save_json(DATA/s['id']/'session.json',public_session(s))
        return result
    finally:s['lock'].release()


def assess_reference(s, payload):
    """Return a reproducible reference-assessment packet without changing runs."""
    from workbench.export_bundle import build_bundle
    from workbench.mask_inputs import decode_mask
    from workbench.reference_evaluation import evaluate_reference, evaluation_packet
    if set(payload)-{'session_id','run_id','reference','source','target','independent','aligned'}:
        raise ValueError('Unsupported reference-evaluation field.')
    if payload.get('aligned') is not True:
        raise ValueError('Confirm that the reference uses the displayed image coordinates.')
    raw = decode_mask(payload.get('reference'))
    if not s['lock'].acquire(blocking=False): raise ValueError('This experiment is busy.')
    try:
        result = next((r for r in s['runs'] if r['id']==payload.get('run_id') and r.get('mask_url')), None)
        if not result: raise ValueError('Select a valid saved mask from this experiment.')
        bundle = build_bundle(DATA/s['id']/'original.png', DATA/s['id']/result['id'])
        record, difference = evaluate_reference(bundle, raw, source=payload.get('source'),
            target=payload.get('target'),independent=payload.get('independent'),created_at=now())
        packet = evaluation_packet(record, difference, bundle, raw)
        assessment_id = uid()
        folder = DATA/s['id']/'assessments'; folder.mkdir(exist_ok=True)
        (folder/(assessment_id+'.zip')).write_bytes(packet)
        return {**record,'difference_png_base64':base64.b64encode(difference).decode('ascii'),
                'packet_url':f'/api/reference-export/{s["id"]}/{assessment_id}'}
    finally: s['lock'].release()


def run_batch(p, progress=None, batch_id=None):
    ids=p.get('session_ids')
    if (not isinstance(ids,list) or not 2<=len(ids)<=5 or
        any(not isinstance(sid,str) or not SID_RE.fullmatch(sid) for sid in ids) or
        len(set(ids))!=len(ids)):
        raise ValueError('A batch requires 2–5 distinct session_ids.')
    sessions=[get_session(sid) for sid in ids]
    if any(s is None for s in sessions):
        raise ValueError('The batch includes an unknown image session.')
    query=p.get('query')
    if not isinstance(query,str) or not query.strip() or len(query)>1800:
        raise ValueError('Enter a batch task of no more than 1,800 characters.')
    if p.get('mode','live') not in ('demo','live'):
        raise ValueError('Unknown runtime mode.')
    if p.get('quality_mode') is not None and (not isinstance(p['quality_mode'],str) or p['quality_mode'] not in ('fast','accurate','auto')):
        raise ValueError('Invalid quality_mode.')
    batch_quality,batch_effective_quality,_=resolve_quality(query,{},p.get('quality_mode'))
    if not has_target_intent(query):
        inherited={s['context'].get('target') for s in sessions}
        if len(inherited)!=1 or None in inherited:
            raise Clarification('Specify a target shared by every image in the batch.')
    batch_id=batch_id or uid()
    results=[]
    for index,s in enumerate(sessions,1):
        item_id=uid()
        item={key:p[key] for key in ('query','mode','quality_mode','roi','scope','force_perception') if key in p}
        item['quality_mode']=batch_quality
        item.update(batch_id=batch_id,item_id=item_id)
        try:
            result=run_task(s,item,allow_batch=True)
            results.append({'item_id':item_id,'session_id':s['id'],'run_id':result['id'],
                            'status':result['status'],'failure_reason':result.get('message') if result['status'] in ('failed','needs_clarification') else None,
                            'metrics':result.get('metrics'),'duration_ms':result['duration_ms']})
        except Exception as exc:
            results.append({'item_id':item_id,'session_id':s['id'],'run_id':None,'status':'failed',
                            'failure_reason':str(exc) if isinstance(exc,ValueError) else type(exc).__name__,
                            'metrics':None,'duration_ms':None})
        if progress:
            progress({'batch_id':batch_id,'status':'running','total_count':len(sessions),
                      'completed_items':len(results),'items':list(results)})
    batch={'batch_id':batch_id,'query':query,'mode':p.get('mode','live'),
           'quality_mode':batch_quality,'effective_quality_mode':batch_effective_quality,'created_at':now(),
           'items':results,'total_count':len(sessions),'completed_count':sum(r['status'] in ('completed','needs_review') for r in results),
           'failed_count':sum(r['status'] in ('failed','needs_clarification') for r in results)}
    folder=DATA/'batches'; folder.mkdir(exist_ok=True)
    save_json(folder/f'{batch_id}.json',batch)
    (folder/f'{batch_id}.csv').write_text(batch_csv(batch),encoding='utf-8')
    return batch

def start_batch(p):
    batch_id=uid()
    with LOCK:
        BATCHES[batch_id]={'batch_id':batch_id,'status':'running','total_count':len(p.get('session_ids',[])) if isinstance(p.get('session_ids'),list) else 0,
                           'completed_items':0,'items':[]}
    def progress(update):
        with LOCK: BATCHES[batch_id]=update
    def worker():
        try:
            result=run_batch(p,progress=progress,batch_id=batch_id)
            with LOCK: BATCHES[batch_id]={**result,'status':'completed','completed_items':len(result['items'])}
        except Exception as exc:
            with LOCK: BATCHES[batch_id]={'batch_id':batch_id,'status':'failed','error':str(exc) if isinstance(exc,ValueError) else type(exc).__name__,
                                         'total_count':BATCHES[batch_id]['total_count'],'completed_items':0,'items':[]}
    threading.Thread(target=worker,daemon=True,name=f'geoscope-batch-{batch_id}').start()
    return BATCHES[batch_id]

def _run_task(s,p,allow_batch=False):
    query=str(p.get('query','')).strip()
    if not query or len(query)>1800: raise ValueError('Enter a task of no more than 1,800 characters.')
    mode=p.get('mode','demo')
    if mode not in ('demo','live'): raise ValueError('Unknown runtime mode.')
    previous=next((r for r in s['runs'] if r['id']==p.get('parent_run_id')),None)
    if p.get('parent_run_id') and previous is None: raise ValueError('The selected parent result does not belong to this image.')
    context=previous.get('task',{}) if previous else s['context']
    start=time.perf_counter(); trace=[]; runid=uid(); folder=DATA/s['id']/runid; folder.mkdir()
    def event(name,detail,state='completed',elapsed=0): trace.append({'step':len(trace)+1,'name':name,'detail':detail,'state':state,'duration_ms':round(elapsed,2),'at':now()})
    result={'id':runid,'session_id':s['id'],'parent_run_id':previous['id'] if previous else None,
            'version':len(s['runs'])+1,'software_version':VERSION,'query':query,'mode':mode,'created_at':now(),'status':'failed','trace':trace,
            'provenance':{'planner':'Procedural demo parser' if mode=='demo' else os.environ.get('GEO_AGENT_MODEL','Not configured'),
                          'perception':'Deterministic synthetic mask from fixtures.py; not a remote-sensing observation or model prediction' if mode=='demo' else 'RemoteSAM service',
                          'source':s['source'],'image_sha256':hashlib.sha256((DATA/s['id']/'original.png').read_bytes()).hexdigest()}}
    image_path=DATA/s['id']/'original.png'
    image=Image.open(image_path).convert('RGB')
    agent_turn=None
    def feedback(payload):
        if agent_turn is None or agent_turn.decision.status!='tool_call': return
        result['tool_feedback']=payload
        try:
            answer=agent_turn.feedback(payload)
            result['agent_feedback']=decision_record(answer)
            if answer.status!='completed':
                result['feedback_warning']='The planner returned no final answer. No additional tool was executed; completed artifacts and measurements are preserved.'
            event('Return tool feedback to RemoteAgent',
                  'Deterministic results returned to the planner. The model response is recorded separately and cannot overwrite measurements.' if answer.status=='completed' else result['feedback_warning'],
                  'completed' if answer.status=='completed' else 'warning')
        except Exception as exc:
            result['feedback_warning']='Planner feedback failed. Completed artifacts and measurements are preserved.'
            result['agent_feedback']={'status':'transport_failed','error_type':type(exc).__name__}
            event('Planner feedback failed',result['feedback_warning'],'warning')
    try:
        event('Load experiment context',f'Image {s["width"]} × {s["height"]}; '+('Use the selected result as context' if context else 'New task'))
        saved_validity=None
        if previous and previous.get('analysis_config'):
            from geomasklab.evidence import build_bundle,load_verified_bundle
            _,saved_validity=load_verified_bundle(build_bundle(image_path,DATA/s['id']/previous['id']))
        try: validate_target_intent(query)
        except ValueError as exc: raise Clarification(str(exc)) from exc
        if batch_requested(query) and not has_target_intent(query) and not context.get('target'):
            raise Clarification('Specify one target for the batch or continue from compatible existing results.')
        roi,roi_source=resolve_roi(query,context,p.get('roi'),s['width'],s['height'])
        quality_mode,effective_quality,quality_source=resolve_quality(query,context,p.get('quality_mode'))
        if roi and p.get('scope') not in (None,'all'):
            raise ValueError('A rectangle ROI and a pixel-half scope cannot be combined.')
        if batch_requested(query) and not allow_batch:
            raise Clarification('Use the batch API to select 2–5 image sessions.')
        result['task_options']={'roi':roi,'roi_source':roi_source,'quality_mode':quality_mode,
                                'effective_quality_mode':effective_quality,'quality_source':quality_source,
                                'batch_id':p.get('batch_id'),'item_id':p.get('item_id')}
        if p.get('simulate_failure'):
            event('Inject controlled demo failure','User-triggered test of tool unavailability','failed')
            raise ValueError('Controlled failure: the tool returned no result. Earlier versions are preserved; no mask or measurements are generated for this run.')
        t=time.perf_counter()
        if mode=='demo':
            plan=parse_task(query,context)
            if plan.get('action')=='segment':
                demo_side,demo_scope_source=resolve_scope(query,context,p.get('scope'))
                if roi and demo_side!='all':
                    raise ValueError('A rectangle ROI and a pixel half cannot be combined. Clear the ROI or select whole-image scope.')
                plan.update(side=demo_side,scope_source=demo_scope_source)
        elif is_export_command(query):
            plan={'action':'export','planner_protocol':'harness_export_command'}
        else:
            dense_task=requires_dense_result(query,context)
            if dense_task and not has_target_intent(query) and not context.get('target'):
                raise Clarification('Specify one semantic target. Extracting the contours of all objects is not supported.')
            invert=resolve_invert(query,context) if dense_task else False
            side,scope_source=resolve_scope(query,context,p.get('scope'))
            if roi and side!='all':
                raise ValueError('A rectangle ROI and a pixel half cannot be combined. Clear the ROI or select whole-image scope.')
            if ambiguous_query(query):
                raise Clarification('Specify a semantic target and pixel scope, or continue from a selected result. No segmentation was executed.')
            agent_turn=AgentTurn(query,image_path,context,side,scope_source,
                                 task_route='dense' if dense_task else 'internal',invert=invert,
                                 roi=roi,quality_mode=quality_mode,batch_id=p.get('batch_id'))
            decision=agent_turn.decision
            result['agent_decision']=decision_record(decision)
            result['provenance']['planner_protocol']='remoteagent'
            if decision.status=='completed':
                if dense_task:
                    raise ValueError('This task requires a mask, but RemoteAgent returned only text. No segmentation tool was called and no measurements were generated.')
                plan={'action':'scene','answer':decision.text,'planner_protocol':'remoteagent'}
            elif decision.status=='tool_call':
                if not dense_task:
                    raise ValueError('This is a scene-response task. The unexpected segmentation call was blocked.')
                plan=segmentation_plan(decision,image_path,side,scope_source,invert=invert,
                                       expected_target=target_intent(query) or context.get('target'))
                event('Validate execution scope',f'Target from validated agent arguments; scope: {SIDES[side]}; source: {scope_source}; segment the whole image before clipping')
            else:
                raise ValueError(f'RemoteAgent decision failed validation ({decision.status}). No tool was executed.')
        event('Interpret task and select route',f'{result["provenance"]["planner"]} · {plan["action"]}',elapsed=(time.perf_counter()-t)*1000)
        if plan['action']=='segment':
            plan.update(roi=roi,roi_source=roi_source,quality_mode=quality_mode,
                        effective_quality_mode=effective_quality,quality_source=quality_source,
                        batch_id=p.get('batch_id'),item_id=p.get('item_id'))
            if mode=='live':
                plan['service_request']['quality_mode']=effective_quality
        result['task']=plan
        if plan.get('target') in TARGET_CAPABILITIES:
            result['capability']={**TARGET_CAPABILITIES[plan['target']],
                                  'semantic_review_required':True,'software_version':VERSION}
        if plan['action']=='clarify':
            result.update(status='needs_clarification',message=plan['question']); event('Request clarification','No segmentation executed','waiting')
        elif plan['action']=='scene':
            if mode=='demo' and not s['sample']: raise ValueError('Scene understanding for uploaded images requires a configured planner and live mode.')
            result.update(status='answered',message=plan.get('answer') if mode=='live' else SAMPLES[s['sample']]['scene'])
            event('Return scene description','This route does not call segmentation tools.')
        elif plan['action']=='export':
            candidate=previous if previous and previous.get('mask_url') else next((r for r in reversed(s['runs']) if r.get('mask_url')),None)
            if not candidate: raise ValueError('No mask result is available for export. Run segmentation first.')
            result.update(status='export_ready',message='The evidence bundle is ready: image, masks, overlay, measurements and execution records.',export_url=candidate['export_url'])
            event('Prepare evidence export','Use the selected or latest valid result without new inference.')
        else:
            target,side=plan['target'],plan['side']; t=time.perf_counter()
            cache_key=mask_cache_key(s,mode,target,plan.get('service_request'))
            cached=DATA/s['id']/previous['id']/'full_mask.png' if previous else None
            reusable=bool(cache_key and previous and previous.get('mask_cache_key')==cache_key and cached.is_file()
                          and not p.get('force_perception') and not re.search(r'重新|重跑|不要复用|\b(?:rerun|re-run|do not reuse|new inference)\b',query,re.I))
            if reusable and hashlib.sha256(cached.read_bytes()).hexdigest()!=previous.get('full_mask_sha256'):
                reusable=False
            if reusable:
                mask=Image.open(cached).convert('L'); event('Reuse full-image mask','Reuse a full mask with matching image, target, prompt and model revision, then apply the current scope.')
                result['provenance']['perception']=previous['provenance']['perception']
                result['reused_from_run_id']=previous['id']
                result['service_metadata']=previous.get('service_metadata',{})
                if result['service_metadata'].get('quality_confirmation')=='legacy_service_unconfirmed':
                    result['task_options']['effective_quality_mode']=None
                    plan['effective_quality_mode']=None
                    plan['quality_confirmation']='legacy_service_unconfirmed'
            elif mode=='demo':
                if not s['sample']: raise ValueError('Uploaded images have no procedural mask. Use live mode or choose a built-in example.')
                if target!=SAMPLES[s['sample']]['target']: raise ValueError(f'This example provides only {TARGETS[SAMPLES[s["sample"]]["target"]].lower()} procedural masks; it cannot establish results for other categories.')
                mask=demo_mask(s['sample']); event('Generate procedural mask','Generated from geometric rules in fixtures.py; no RemoteSAM call.',elapsed=(time.perf_counter()-t)*1000)
            else:
                url=os.environ.get('GEO_REMOTESAM_URL','')
                if not url: raise ValueError('RemoteSAM is not configured. No segmentation was executed.')
                data=post_json(url,{**plan['service_request'],'image':image_b64(image)})
                confirmed_quality=data.get('quality_mode')
                if confirmed_quality!=effective_quality:
                    if confirmed_quality is not None or quality_mode!='auto' or p.get('quality_mode') is not None:
                        raise ValueError('RemoteSAM did not confirm the selected execution mode; the result cannot be labeled with that mode.')
                    result['task_options']['effective_quality_mode']=None
                    plan['effective_quality_mode']=None
                    plan['quality_confirmation']='legacy_service_unconfirmed'
                encoded=data.get('masks',{}).get(plan['mask_field']) if plan.get('mask_field') else data.get('mask')
                if data.get('status')!='success' or not encoded: raise ValueError('RemoteSAM returned no valid mask.')
                mask=Image.open(io.BytesIO(base64.b64decode(encoded,validate=True))).convert('L')
                if mask.size!=image.size: raise ValueError('RemoteSAM mask dimensions do not match the image. Check the service coordinate restoration.')
                result['service_metadata']={key:data[key] for key in (
                    'model','timing_ms','quality','quality_mode','requested_quality_mode',
                    'parameters','service_version','mode_parameters',
                    'original_size','output_size','peak_vram_mb') if key in data}
                if 'candidate_stats' in data:
                    result['service_metadata']['full_mask_candidate_stats']=data['candidate_stats']
                if confirmed_quality is None:
                    result['service_metadata']['quality_confirmation']='legacy_service_unconfirmed'
                event('Run RemoteSAM segmentation','Live service call; spatial scope is applied by deterministic geometry.',elapsed=(time.perf_counter()-t)*1000)
            mask=binary_mask(mask)
            if mask.size!=image.size: raise ValueError('Full-mask dimensions do not match the image.')
            mask.save(folder/'full_mask.png')
            result['mask_cache_key']=cache_key
            result['full_mask_sha256']=hashlib.sha256((folder/'full_mask.png').read_bytes()).hexdigest()
            result['provenance']['perception_revision']='synthetic-fixtures-v1' if mode=='demo' else os.environ.get('GEO_REMOTESAM_REVISION','Not recorded')
            if plan.get('invert'):
                mask=ImageOps.invert(mask)
            full_mask=mask
            mask=constrain(mask,side,roi)
            if saved_validity is not None:
                from geomasklab.domain import valid_image,validity_measurements,configuration,add_validity_statistics
                valid=valid_image(saved_validity,image.size)
                mask,_,_=validity_measurements(full_mask,plan,valid)
                declaration=json.loads(saved_validity['analysis.json'])['validity']
                result['analysis_config']=configuration(plan,result['provenance']['image_sha256'],image.size,declaration)
                for name in ('valid_mask.png','source_valid_mask.png'):
                    if name in saved_validity:(folder/name).write_bytes(saved_validity[name])
                save_json(folder/'analysis.json',result['analysis_config'])
            metrics=statistics(mask,side,roi,full_mask)
            if saved_validity is not None:add_validity_statistics(metrics,full_mask,plan,valid)
            event('Apply scope and measure pixels',f'{SIDES[side]}; whole-image denominator: {image.width*image.height:,} pixels; saved validity retained when present')
            overlay=image.copy(); tint=Image.new('RGB',image.size,(69,213,152)); colored=Image.blend(image,tint,.48); overlay.paste(colored,(0,0),mask)
            mask.save(folder/'mask.png'); overlay.save(folder/'overlay.png')
            status='completed' if metrics['pixel_area'] else 'needs_review'
            event('Verify result artifacts','Dimensions, scope, measurements and files checked; semantic accuracy requires separate review.')
            base=f'/experiments/{s["id"]}/{runid}'
            result.update(status=status,metrics=metrics,mask_url=base+'/mask.png',overlay_url=base+'/overlay.png',export_url=f'/api/export/{s["id"]}/{runid}',
              message=f'{SIDES[side]} {"non-" if plan.get("invert") else ""}{TARGETS[target].lower()}: {metrics["pixel_area"]:,} foreground pixels; {metrics["area_ratio"]*100:.2f}% whole-image coverage. '+('Procedural software demonstration; no model inference.' if mode=='demo' else 'Review target identity and boundaries using the overlay.') if metrics['pixel_area'] else 'No foreground was detected. Review this result; an empty mask does not prove target absence.')
            if mode=='live' and TARGET_CAPABILITIES[target]['level']=='experimental':
                result['message']+=' This category is experimental and has no frozen semantic evaluation.'
            s['context']={'target':target,'side':side,'invert':bool(plan.get('invert')),
                          'roi':roi,'quality_mode':quality_mode}; save_json(folder/'statistics.json',metrics)
            if mode=='live':
                feedback({'status':'success','tool_name':plan['tool_name'],'metrics':metrics,
                          'scope_rule':plan['scope_rule'],'actual_service_request':plan['service_request'],
                          'artifact_ids':{'session_id':s['id'],'run_id':runid,'mask_url':result['mask_url']},
                          'reused_from_run_id':result.get('reused_from_run_id'),
                          'service_metadata':result.get('service_metadata',{})})
                if result.get('feedback_warning'): result['message']+=' '+result['feedback_warning']
    except Clarification as exc:
        result.update(status='needs_clarification',message=str(exc))
        event('Request clarification',str(exc),'waiting')
    except Exception as exc:
        result.update(status='failed',message=str(exc) if isinstance(exc,ValueError) else f'Service request failed ({type(exc).__name__}). Check the configured services.')
        if not trace or trace[-1]['state']!='failed': event('Execution failed',result['message'],'failed')
        feedback({'status':'error','message':result['message'],'artifacts_created':False})
    result['duration_ms']=round((time.perf_counter()-start)*1000,2)
    if result.get('mask_url'):
        result['semantic_review']=initial_review()
        result['report_url']=f'/api/report/{s["id"]}/{runid}'
        (folder/'report.md').write_text(experiment_report(s,result),encoding='utf-8')
    save_json(folder/'result.json',{k:v for k,v in result.items() if k!='trace'}); save_json(folder/'run_log.json',trace)
    s['runs'].append(result); save_json(DATA/s['id']/'session.json',public_session(s)); return result

class Handler(SimpleHTTPRequestHandler):
    def __init__(self,*a,**kw): super().__init__(*a,directory=str(WEB),**kw)
    def json(self,value,status=200):
        raw=json.dumps(value,ensure_ascii=False).encode(); self.send_response(status); self.send_header('Content-Type','application/json; charset=utf-8'); self.send_header('Cache-Control','no-store'); self.send_header('Content-Length',str(len(raw))); self.end_headers(); self.wfile.write(raw)
    def do_GET(self):
        path=self.path.split('?')[0]
        if path.startswith(('/api/comparison-export/','/api/component-export/')):
            identifier=path.rsplit('/',1)[-1]
            if not re.fullmatch(r'[a-f0-9]{24}',identifier):return self.send_error(404)
            kind='comparisons' if path.startswith('/api/comparison-export/') else 'inspections'
            file=DATA/kind/(identifier+'.zip')
            if not file.is_file():return self.send_error(404)
            raw=file.read_bytes();self.send_response(200)
            self.send_header('Content-Type','application/zip')
            self.send_header('Content-Disposition',f'attachment; filename="geomasklab-{kind}-{identifier}.zip"')
            self.send_header('Content-Length',str(len(raw)));self.end_headers();return self.wfile.write(raw)
        if path.startswith(('/api/offline-batch/','/api/offline-batch-export/')):
            from workbench.offline_workflows import get_offline_batch,export_offline_batch
            try:
                identifier=path.rsplit('/',1)[-1]
                if path.startswith('/api/offline-batch/'):
                    return self.json(get_offline_batch(DATA,identifier))
                raw=export_offline_batch(DATA,identifier)
                self.send_response(200);self.send_header('Content-Type','application/zip')
                self.send_header('Content-Disposition',f'attachment; filename="geomasklab-batch-{identifier}.zip"')
                self.send_header('Content-Length',str(len(raw)));self.end_headers();return self.wfile.write(raw)
            except (ValueError,KeyError,OSError):return self.json({'error':'Offline batch is unavailable or its saved artifacts failed verification.'},400)
        if path=='/api/status': return self.json({**settings_status(),'samples':SAMPLES,'version':VERSION,'capabilities':capabilities()})
        if path=='/api/sessions': return self.json({'sessions':session_index()})
        if path.startswith('/api/reference-export/'):
            parts=path.strip('/').split('/')
            if len(parts)!=4 or not all(SID_RE.fullmatch(p) for p in parts[2:]):return self.send_error(404)
            file=DATA/parts[2]/'assessments'/(parts[3]+'.zip')
            if not file.is_file():return self.send_error(404)
            raw=file.read_bytes();self.send_response(200)
            self.send_header('Content-Type','application/zip')
            self.send_header('Content-Disposition',f'attachment; filename="geomasklab-reference-{parts[3]}.zip"')
            self.send_header('Content-Length',str(len(raw)));self.end_headers();return self.wfile.write(raw)
        if path.startswith('/api/ledger/'):
            s=get_session(path.rsplit('/',1)[-1])
            if not s: return self.json({'error':'Experiment not found.'},404)
            from workbench.experiment_management import ledger_csv
            with s['lock']: raw=ledger_csv(s).encode('utf-8')
            self.send_response(200)
            self.send_header('Content-Type','text/csv; charset=utf-8')
            self.send_header('Content-Disposition',f'attachment; filename="geomasklab_{s["id"]}_results.csv"')
            self.send_header('Content-Length',str(len(raw)));self.end_headers()
            return self.wfile.write(raw)
        if path.startswith('/api/batch/'):
            bid=path.rsplit('/',1)[-1]
            if not SID_RE.fullmatch(bid): return self.json({'error':'Invalid batch ID.'},404)
            with LOCK: batch=BATCHES.get(bid)
            if batch is None:
                file=DATA/'batches'/f'{bid}.json'
                if file.is_file(): batch={**json.loads(file.read_text(encoding='utf-8')),'status':'completed'}
            return self.json(batch) if batch else self.json({'error':'Batch not found.'},404)
        if path.startswith('/api/batch-export/'):
            bid=path.rsplit('/',1)[-1]
            if not SID_RE.fullmatch(bid): return self.send_error(404)
            file=DATA/'batches'/f'{bid}.csv'
            if not file.is_file(): return self.send_error(404)
            raw=file.read_bytes(); self.send_response(200)
            self.send_header('Content-Type','text/csv; charset=utf-8')
            self.send_header('Content-Disposition',f'attachment; filename="geomasklab_batch_{bid}.csv"')
            self.send_header('Content-Length',str(len(raw))); self.end_headers(); return self.wfile.write(raw)
        if path.startswith('/api/session/'):
            sid=path.rsplit('/',1)[-1]; s=get_session(sid)
            return self.json(public_session(s)) if s else self.json({'error':'Session not found or persisted files incomplete.'},404)
        if path.startswith('/api/export/'):
            parts=path.split('/'); sid,rid=parts[-2:]
            if len(parts)!=5 or not SID_RE.fullmatch(sid) or not SID_RE.fullmatch(rid): return self.send_error(404)
            folder=DATA/sid/rid
            if not (folder/'mask.png').exists(): return self.send_error(404)
            from workbench.export_bundle import build_bundle
            s=get_session(sid)
            if not s: return self.send_error(404)
            with s['lock']: raw=build_bundle(DATA/sid/'original.png',folder)
            self.send_response(200); self.send_header('Content-Type','application/zip'); self.send_header('Content-Disposition',f'attachment; filename="geomasklab_{rid}.zip"'); self.send_header('Content-Length',str(len(raw))); self.end_headers(); return self.wfile.write(raw)
        if path.startswith('/api/report/'):
            parts=path.split('/'); sid,rid=parts[-2:]
            if len(parts)!=5 or not SID_RE.fullmatch(sid) or not SID_RE.fullmatch(rid): return self.send_error(404)
            file=DATA/sid/rid/'report.md'
            if not file.is_file(): return self.send_error(404)
            s=get_session(sid)
            if not s: return self.send_error(404)
            with s['lock']: raw=file.read_bytes()
            self.send_response(200)
            self.send_header('Content-Type','text/markdown; charset=utf-8')
            self.send_header('Content-Disposition',f'attachment; filename="geomasklab_{rid}_report.md"')
            self.send_header('Content-Length',str(len(raw))); self.end_headers(); return self.wfile.write(raw)
        if path.startswith('/experiments/'):
            parts=path.strip('/').split('/')
            if len(parts) not in (3,4) or not SID_RE.fullmatch(parts[1]) or (len(parts)==4 and not SID_RE.fullmatch(parts[2])) or parts[-1] not in ('original.png','mask.png','overlay.png'): return self.send_error(404)
            file=DATA.joinpath(*parts[1:])
            if not file.is_file(): return self.send_error(404)
            raw=file.read_bytes(); self.send_response(200); self.send_header('Content-Type','image/png'); self.send_header('Content-Length',str(len(raw))); self.end_headers(); return self.wfile.write(raw)
        return super().do_GET()
    def do_POST(self):
        try:
            length=int(self.headers.get('Content-Length','0'))
            limit=48*1024*1024 if self.path=='/api/offline-batch/start' else 18*1024*1024
            if length<=0 or length>limit: raise ValueError('Unsupported request size.')
            p=json.loads(self.rfile.read(length))
            if self.path.startswith('/api/offline-batch/'):
                from workbench.offline_workflows import start_offline_batch,cancel_offline_batch,resume_offline_batch,offline_batch_evidence
                if self.path=='/api/offline-batch/start':return self.json(start_offline_batch(DATA,p))
                if self.path=='/api/offline-batch/cancel':return self.json(cancel_offline_batch(DATA,p.get('id')))
                if self.path=='/api/offline-batch/resume':return self.json(resume_offline_batch(DATA,p.get('id')))
                if self.path=='/api/offline-batch/open-result':
                    raw=offline_batch_evidence(DATA,p.get('id'),p.get('sample_id'))
                    return self.json(import_evidence({'bundle':base64.b64encode(raw).decode('ascii'),'name':'Batch sample '+str(p.get('sample_id'))}))
            if self.path=='/api/verify-review-packet':
                from workbench.offline_workflows import verify_uploaded_packet
                return self.json(verify_uploaded_packet(p.get('packet')))
            if self.path=='/api/inspect-components':
                s=get_session(p.get('session_id'))
                if not s:raise ValueError('Experiment not found.')
                selected=next((r for r in s['runs'] if r['id']==p.get('run_id') and r.get('mask_url')),None)
                if not selected:raise ValueError('Select a saved mask result before inspecting candidates.')
                from workbench.export_bundle import build_bundle
                from workbench.offline_workflows import save_inspection
                if not s['lock'].acquire(blocking=False):raise ValueError('This experiment is busy.')
                try:
                    bundle=build_bundle(DATA/s['id']/'original.png',DATA/s['id']/selected['id'])
                    return self.json(save_inspection(DATA,bundle,min_area_pixels=p.get('min_area_pixels',1),boundary_filter=p.get('boundary_filter','all')))
                finally:s['lock'].release()
            if self.path=='/api/check-services': return self.json(inspect_services())
            if self.path=='/api/session': return self.json(new_session(p.get('sample','urban'),p.get('image'),p.get('name')))
            if self.path=='/api/import': return self.json(import_evidence(p))
            if self.path in ('/api/import-mask','/api/evaluate-reference'):
                s=get_session(p.get('session_id'))
                if not s: raise ValueError('Experiment not found. Select an image first.')
                return self.json(import_mask(s,p) if self.path=='/api/import-mask' else assess_reference(s,p))
            if self.path=='/api/session/update':
                s=get_session(p.get('session_id'))
                if not s: raise ValueError('Experiment not found.')
                from workbench.experiment_management import metadata_changes
                changes=metadata_changes(p)
                if not s['lock'].acquire(blocking=False): raise ValueError('This experiment is busy.')
                try:
                    s.update(changes)
                    save_json(DATA/s['id']/'session.json',public_session(s))
                    return self.json(public_session(s))
                finally: s['lock'].release()
            if self.path=='/api/compare-results':
                s=get_session(p.get('session_id'))
                if not s: raise ValueError('Experiment not found.')
                a,b=p.get('run_a'),p.get('run_b')
                if a==b: raise ValueError('Choose two different result versions.')
                selected=[next((r for r in s['runs'] if r['id']==rid and r.get('mask_url')),None) for rid in (a,b)]
                if not all(selected): raise ValueError('Choose two valid mask results from this experiment.')
                from workbench.export_bundle import build_bundle
                from workbench.offline_workflows import save_comparison
                if not s['lock'].acquire(blocking=False): raise ValueError('This experiment is busy.')
                try:
                    bundles=[build_bundle(DATA/s['id']/'original.png',DATA/s['id']/r['id']) for r in selected]
                    return self.json(save_comparison(DATA,bundles,domain_policy=p.get('domain_policy','intersection')))
                finally: s['lock'].release()
            if self.path=='/api/recalculate-region':
                s=get_session(p.get('session_id'))
                if not s: raise ValueError('Session not found. Select an image first.')
                return self.json(recalculate_region(s,p))
            if self.path=='/api/run':
                s=get_session(p.get('session_id'))
                if not s: raise ValueError('Session not found. Choose the image again.')
                return self.json(run_task(s,p))
            if self.path=='/api/review':
                s=get_session(p.get('session_id'))
                if not s: raise ValueError('Session not found. Choose the image again.')
                return self.json(review_result(s,p))
            if self.path=='/api/batch': return self.json(run_batch(p))
            if self.path=='/api/batch/start': return self.json(start_batch(p))
            return self.json({'error':'Endpoint not found.'},404)
        except (ValueError,KeyError,Image.UnidentifiedImageError) as exc: return self.json({'error':str(exc)},400)
        except Exception: return self.json({'error':'Could not process the image or request. Check the input format.'},500)

if __name__=='__main__':
    port=int(os.environ.get('GEO_PORT','4180'))
    print(f'GeoMaskLab: http://127.0.0.1:{port}',flush=True)
    ThreadingHTTPServer(('127.0.0.1',port),Handler).serve_forever()
